### ISSUE TITLE
error when running with 1.7.0

### ISSUE THREAD

**Issue by garbled1** [mansuf/mangadex-downloader#28] opened 2022-08-23 19:38 UTC
```shell
$ /home/mxdl/venv/bin/mangadex-dl -dr 1 -ngn --language en --save-as cbz --folder /comics/Manga https://mangadex.org/title/78abd677-3058-4a71-8dd4-1d687e5a1e64/how-to-kill-a-god --start-chapter 50 --end-chapter 51
Error: 'None' is not valid value, available values are ['cloudflare', 'cloudflare-security', 'cloudflare-family', 'opendns', 'opendns-family', 'adguard', 'adguard-family', 'adguard-unfiltered', 'quad9', 'quad9-unsecured', 'google']
```

**Comment by mansuf** [comment] 2022-08-24 00:28
Yep confirmed, it is broken because of DNS-over-HTTPS thing. You can **temporary** fix by using `-doh <provider>`  option. 

On my way to fix this.

**Comment by mansuf** [comment] 2022-08-24 00:55
Fixed in https://github.com/mansuf/mangadex-downloader/commit/73d80914fb24714317a695591d7fbeb787a29f4e and https://github.com/mansuf/mangadex-downloader/commit/e00a89ec557e5eae5c561f9ee3b2812f375cf9db

**Comment by mansuf** [comment] 2022-08-24 01:06
Released in [v1.7.1](https://github.com/mansuf/mangadex-downloader/releases/tag/v1.7.1)

**Closed by mansuf** 2022-08-24 01:06 UTC

**Comment by garbled1** [comment] 2022-08-24 13:08
Does this new version force usage of dns over https?  Or does it only do it if I give that option?

**Comment by mansuf** [comment] 2022-08-24 13:10
Nope, optional only. You can enable dns over https by providing `-doh` or `--dns-over-https` option
