### ISSUE TITLE
add more meta to downloadfile.json

### ISSUE THREAD

**Issue by benpoe** [mansuf/mangadex-downloader#47] opened 2023-02-09 07:02 UTC
### The idea

since you've already created a downloaded [json.file](https://github.com/mansuf/mangadex-downloader/issues/45#issuecomment-1416701955).
maybe you can add more meta data to it? like for instance the download ID,  link, or more important: manga description,tags, last update, last download time etc.

### Why this feature should be added to the app ?

this would be easy to reuse the json file in a script to fill up a series metadata and redownload at set times with a script.

**Comment by mansuf** [comment] 2023-02-10 16:29
Yes, but in sqlite file not in JSON. See #48 

Please note that i'm only adding "last download time" and "manga id" as it related to download tracker. It was intended for download tracker only not for manga manifest or metadata

**Comment by mansuf** [comment] 2023-02-25 06:48
Added in https://github.com/mansuf/mangadex-downloader/pull/49/commits/1b125c73138fb4fafec0964ee205d2f52ba851b9. Will be released soon in v2.8.0

**Closed by mansuf** 2023-02-25 06:48 UTC
Labels: enhancement
