### ISSUE TITLE
Don't re-download cover every time

### ISSUE THREAD

**Issue by garbled1** [mansuf/mangadex-downloader#23] opened 2022-08-09 15:09 UTC
I use this to re-update manga I read into komga on a timed basis, but it re-downloads the cover.jpg every time it visits a manga, so my komga directory always shows up as modified.  Would it be possible to add an option to only download the cover if it is missing, or even changed?

**Comment by mansuf** [comment] 2022-08-10 03:07
It was an issue caused by [this line of code](https://github.com/mansuf/mangadex-downloader/blob/v1.4.0/mangadex_downloader/main.py#L407). The argument `replace` should be `False` not `True`, i don't know why i did that in the first place. Sorry about that

**Comment by mansuf** [comment] 2022-08-10 03:18
Fixed in https://github.com/mansuf/mangadex-downloader/commit/c8f1045f654198ea8b27f5773c252bc4a195839e, thank you !

**Closed by mansuf** 2022-08-10 03:18 UTC
