### ISSUE TITLE
PDF conversion errors out with "image file is truncated", simple fix needed to error handling

### ISSUE THREAD

**Issue by JacekJagosz** [mansuf/mangadex-downloader#54] opened 2023-03-03 23:37 UTC
### What happened ?

When downloading a volume with PDF conversion enabled it will error out with `OSError: image file is truncated (34 bytes not processed)`
This is a well know error, with already implemented error handling. But that error handling doesn't work in my case.
The problematic piece of code, in `mangadex_downloader/format/pdf.py`:
```
def check_truncated(self, img):
        # Pillow won't load truncated images
        # See https://github.com/python-pillow/Pillow/issues/1510
        # Image reference: https://mangadex.org/chapter/1615adcb-5167-4459-8b12-ee7cfbdb10d9/16
        err = None
        try:
            img.load()
        except OSError as e:
            err = e
        else:
            return False

        if err and 'broken data stream' in str(err):
            ImageFile.LOAD_TRUNCATED_IMAGES = True
        elif err:
            # Other error
            raise err

        # Load it again
        img.load()

        return True
```
In my case it enters the `elif`, instead of the conditional that was meant to deal with this issue. What I did is I just moved `ImageFile.LOAD_TRUNCATED_IMAGES = True` before fist img.load() and it fixed this issue. I guess you could alter the `if` statement so this would work too.

### What did you expect to happen ?

Conditional meant to handle this error to catch it.

### OS version

Solus 4.3 (Linux)

### App version

```
mangadex-downloader v2.8.0 (https://github.com/mansuf/mangadex-downloader)
Python: 3.10.9
arch: x64
bundled executable: no
```

### Installation origin

PyPI (Python Package Index)

### Reproducible command

`mangadex-dl --save-as pdf-volume --start-chapter 4 https://mangadex.org/title/34f45c13-2b78-4900-8af2-d0bb551101f4/dorohedoro`

### Additional context

Full error log:

```
[INFO] Vol. 4 has finished download, converting to pdf...
pdf_progress:   1%|▋                                                                                                                                      | 1/186 [00:00<00:30,  6.14item/s][ERROR] We have problem in queue worker
Traceback (most recent call last):
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/utils.py", line 214, in run
    job()
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/format/pdf.py", line 491, in <lambda>
    worker.submit(lambda: self.convert(images, pdf_file))
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/format/pdf.py", line 390, in convert
    im.save(
  File "/home/jacek/.local/lib/python3.10/site-packages/PIL/Image.py", line 2353, in save
    save_handler(self, fp, filename)
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/format/pdf.py", line 108, in _save_all
    self._save(im, fp, filename, save_all=True)
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/format/pdf.py", line 190, in _save
    truncated = self.check_truncated(im)
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/format/pdf.py", line 100, in check_truncated
    raise err
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/format/pdf.py", line 90, in check_truncated
    img.load()
  File "/home/jacek/.local/lib/python3.10/site-packages/PIL/ImageFile.py", line 254, in load
    raise OSError(
OSError: image file is truncated (34 bytes not processed)
Stack (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/utils.py", line 216, in run
    log.error("We have problem in queue worker", exc_info=err, stack_info=True)
[ERROR] Unhandled exception, OSError: image file is truncated (34 bytes not processed)
Traceback (most recent call last):
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/cli/__init__.py", line 73, in _main
    download(args)
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/cli/download.py", line 33, in download
    url(args, args.type)
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/cli/url.py", line 161, in __call__
    self.func(self.id, args)
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/cli/url.py", line 95, in download_manga
    dl_manga(*args)
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/main.py", line 163, in download
    download_manga(manga, base_path)
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/main.py", line 133, in download_manga
    fmt.main()
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/format/base.py", line 539, in main
    self.download_volumes(worker, volumes)
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/format/pdf.py", line 491, in download_volumes
    worker.submit(lambda: self.convert(images, pdf_file))
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/utils.py", line 196, in submit
    raise err
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/utils.py", line 214, in run
    job()
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/format/pdf.py", line 491, in <lambda>
    worker.submit(lambda: self.convert(images, pdf_file))
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/format/pdf.py", line 390, in convert
    im.save(
  File "/home/jacek/.local/lib/python3.10/site-packages/PIL/Image.py", line 2353, in save
    save_handler(self, fp, filename)
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/format/pdf.py", line 108, in _save_all
    self._save(im, fp, filename, save_all=True)
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/format/pdf.py", line 190, in _save
    truncated = self.check_truncated(im)
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/format/pdf.py", line 100, in check_truncated
    raise err
  File "/home/jacek/.local/lib/python3.10/site-packages/mangadex_downloader/format/pdf.py", line 90, in check_truncated
    img.load()
  File "/home/jacek/.local/lib/python3.10/site-packages/PIL/ImageFile.py", line 254, in load
    raise OSError(
OSError: image file is truncated (34 bytes not processed)
pdf_progress:   1%|█
```

**Comment by mansuf** [comment] 2023-03-04 01:49
Well, the `check_truncated()` function is to handle missing end header on some images. Normally, if error `OSError: image file is truncated (xx bytes not processed)` is happened, i would assume that the image is not downloaded correctly. But this is just broken image on MangaDex itself.

Anyway, the issue is fixed in https://github.com/mansuf/mangadex-downloader/commit/f09ef8884d5b9fe1eec80989e057644ac0065120 and will be released in `v2.8.1` soon

**Closed by mansuf** 2023-03-04 01:49 UTC
Labels: bug
