### ISSUE TITLE
Duplicate scanlation groups

### ISSUE THREAD

**Issue by TechnologyMan101** [mansuf/mangadex-downloader#11] opened 2022-03-31 19:41 UTC
Environment Information:
mangadex-dl = latest commit from GitHub (as of 67db5fe)
Operating System = macOS 12.3 Monterey (Intel)
Python Version = 3.10 (installed from the pkg from python.org)

Installation Method:
GitHub latest commit = `git clone https://github.com/mansuf/mangadex-downloader.git && cd mangadex-downloader && python3 ./setup.py install`

I was attempting to download groups separately for one chapter, as its group naming was causing issues for me and the downloader (treated as same group, though it had 2 group names)

`mangadex-dl --save-as cbz --type chapter "b753b4b6-cc2f-4d47-ad32-634ce70f1399"`
This command was used to save a chapter. I tested multiple chapters with the same result. 

```[INFO] Fetching chapter b753b4b6-cc2f-4d47-ad32-634ce70f1399
[INFO] Found chapter 1 from manga "Karakai Jouzu no Takagi-san"
[INFO] Using cbz format
[ERROR] Unhandled exception, TypeError: BaseFormat.__init__() missing 1 required positional argument: 'kwargs_iter_chapter_img'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mangadex_downloader-0.6.1-py3.10.egg/mangadex_downloader/cli/__init__.py", line 41, in _main
    download(args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mangadex_downloader-0.6.1-py3.10.egg/mangadex_downloader/cli/download.py", line 12, in download
    url(args, args.type)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mangadex_downloader-0.6.1-py3.10.egg/mangadex_downloader/cli/url.py", line 126, in __call__
    self.func(self.id, args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mangadex_downloader-0.6.1-py3.10.egg/mangadex_downloader/cli/url.py", line 72, in download_chapter
    dl_chapter(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mangadex_downloader-0.6.1-py3.10.egg/mangadex_downloader/main.py", line 414, in download_chapter
    fmt = fmt_class(
TypeError: BaseFormat.__init__() missing 1 required positional argument: 'kwargs_iter_chapter_img'
```
This is the received error.

**Comment by mansuf** [comment] 2022-03-31 23:42
The error caused by legacy sorting feature (#10) . It's not yet implemented when downloading a chapter or list.

Also, as of commit https://github.com/mansuf/mangadex-downloader/commit/921150fe7cb13753bf61851bcffdd619df5b887a (the working one). The group filter only works when downloading a manga.

I will implement it soon after i done with legacy sorting feature.

> I was attempting to download groups separately for one chapter, as its group naming was causing issues for me and the downloader (treated as same group, though it had 2 group names)

Yes, the app only looking for single scanlation group in 1 chapter. Once it found the group, it will use that group name. I will fix this soon after i done with legacy sorting feature.

Thanks for the info !

**Comment by mansuf** [comment] 2022-04-01 03:46
I do have one question about:

> I was attempting to download groups separately for one chapter, as its group naming was causing issues for me and the downloader (treated as same group, though it had 2 group names)

What do you mean about "download groups separately for one chapter" ?
All i know is you can "download all same chapters but with different groups", but i think "download one chapter but separated groups" is not possible.

**Comment by TechnologyMan101** [comment] 2022-04-01 04:26
I'm not sure how the program was reacting to it, but it seems to attempt to download both groups of Chapter 1 when I did `--group "all"`. While it did seem to attempt to download all, it still treated both as "Ciel Scans," while one group upload was "teakhanirons & Ciel Scans" (it had 2 groups listed, with a long space separating the names). This resulted in the program overwriting the chapter instead of creating a different file. I would expect the program to handle an upload with multiple group names as something like "groupA & groupB" to avoid issues.

**Comment by TechnologyMan101** [comment] 2022-04-01 04:28
Forgot to mention in my last comment, but you can see the weird group name scheme in Chapter 1 on this page: https://mangadex.org/title/6e445564-d9a8-4862-bff1-f4d6be6dba2c/karakai-jouzu-no-takagi-san?page=9

**Comment by mansuf** [comment] 2022-04-01 06:12
![image](https://user-images.githubusercontent.com/43638783/161205404-1a6a03a4-09f3-4e23-b934-2723cdc89077.png)

Yeah, i can see that the app cannot handle multiple groups in one chapter. On my way to fix this.

Thanks for the explanation !

**Comment by mansuf** [comment] 2022-04-02 01:23
Fixed in https://github.com/mansuf/mangadex-downloader/commit/300045e32340cf2f9582aac98c06ef9ea0600403

**Closed by mansuf** 2022-04-02 01:23 UTC
